# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'colorize', '~> 0.8.1'
gem 'pry', '~> 0.14.1'
gem "tty-prompt"
gem "unirest"
gem "faker"
gem "activerecord"
gem "sqlite3"
gem "rake"
